{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recurse-center-tweet-listener.fullname" . }}
  labels:
    {{- include "recurse-center-tweet-listener.labels" . | nindent 4 }}
type: Opaque
data:
  twitter-consumer-key: "{{ .Values.application.twitter.secrets.consumerKey | b64enc }}"
  twitter-consumer-key-secret: "{{ .Values.application.twitter.secrets.consumerKeySecret | b64enc }}"
  twitter-access-token: "{{ .Values.application.twitter.secrets.accessToken | b64enc }}"
  twitter-access-token-secret: "{{ .Values.application.twitter.secrets.accessTokenSecret | b64enc }}"
{{- end }}
